#!/bin/bash
CLONE_DIR="./"  # updated when repository is cloned

# Check if a file argument is provided
if [ $# -eq 0 ]; then
    echo "Usage: $0 <file>"
    exit 1
fi

# Check if the provided file exists
if [ ! -f "$1" ]; then
    echo "Error: File '$1' not found."
    exit 1
fi

# Run the Python script with the provided file as input
python "$CLONE_DIR/vib_animate.py" "$1"
